//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skin_Thickness_Evaluation {
    
    
    public partial class UC096 {
        
        /// <summary>
        /// BladeList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Skin_Thickness_Evaluation.Components.Filter.Filter_BladeList BladeList1;
        
        /// <summary>
        /// MetalRemoval01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Skin_Thickness_Evaluation.Components.UC_MetalRemoval MetalRemoval01;
    }
}
