//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skin_Thickness_Evaluation.SITServiceExt {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="uri:SIEMENS/SIMATIC-IT/WebServiceExt", ConfigurationName="SITServiceExt.SITServiceExtSoap")]
    public interface SITServiceExtSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="uri:SIEMENS/SIMATIC-IT/WebServiceExt/ServiceTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServiceTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="uri:SIEMENS/SIMATIC-IT/WebServiceExt/ServiceCaller", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ServiceCaller(string dataInput, ref int errorCode, ref string errorDescription, ref string dataOutput, ref System.Data.DataSet dataRows);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SITServiceExtSoapChannel : Skin_Thickness_Evaluation.SITServiceExt.SITServiceExtSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SITServiceExtSoapClient : System.ServiceModel.ClientBase<Skin_Thickness_Evaluation.SITServiceExt.SITServiceExtSoap>, Skin_Thickness_Evaluation.SITServiceExt.SITServiceExtSoap {
        
        public SITServiceExtSoapClient() {
        }
        
        public SITServiceExtSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SITServiceExtSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SITServiceExtSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SITServiceExtSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServiceTest() {
            return base.Channel.ServiceTest();
        }
        
        public void ServiceCaller(string dataInput, ref int errorCode, ref string errorDescription, ref string dataOutput, ref System.Data.DataSet dataRows) {
            base.Channel.ServiceCaller(dataInput, ref errorCode, ref errorDescription, ref dataOutput, ref dataRows);
        }
    }
}
